---
alt_send_esc: true
bell:
  animation: EaseOutExpo
  color: '#000000'
  duration: 10
cursor:
  blink_interval: 550
  blink_timeout: 0
  style:
    blinking: Always
font:
  bold:
    style: Bold
  draw_bold_text_with_bright_colors: true
  italic:
    family: Iosevka Nerd Font Mono
    style: Italic
  normal:
    family: Iosevka Nerd Font Mono
  size: 16.0
import:
  - ~/.config/alacritty/base16_default_dark.yml
  - ~/.config/alacritty/keybindings.yml
live_config_reload: true
selection:
  save_to_clipboard: true
shell:
  args:
    - -l
    - -c
    - 'tmux attach || tmux'
  program: /bin/zsh
window:
  decorations: none
  dynamic_padding: true
