env:
  TERM:                              xterm-256color

window:
  dimensions:
    columns:                         80
    lines:                           24
  padding:
    x:                               2
    y:                               2
  dynamic_padding:                   false
  decorations:                       full
  opacity:                           1.0
  dynamic_title:                     true
  scrolling:
    history:                         10000
    multiplier:                      3

font:
  normal:
    family:                          BlexMono Nerd Font Mono
    style:                           Book
  bold:
    family:                          BlexMono Nerd Font Mono
    style:                           Bold
  italic:
    family:                          BlexMono Nerd Font Mono
    style:                           Text Italic
  bold_italic:
    family:                          BlexMono Nerd Font Mono
    style:                           SemiBold Italic
  size:                              14
  offset:
    x:                               0
    y:                               0
  glyph_offset:
    x:                               0
    y:                               0
  draw_bold_text_with_bright_colors: true
  builtin_box_drawing:               true

colors:
# Base16 3024 256 - alacritty color config
# Jan T. Sott (http://github.com/idleberg)
  primary:
    background:                      '0x141414'
    foreground:                      '0xa5a2a2'
  cursor:
    text:                            '0x090300'
    cursor:                          '0xa5a2a2'
  normal:
    black:                           '0x090300'
    red:                             '0xdb2d20'
    green:                           '0x01a252'
    yellow:                          '0xfded02'
    blue:                            '0x01a0e4'
    magenta:                         '0xa16a94'
    cyan:                            '0xb5e4f4'
    white:                           '0xa5a2a2'
  bright:
    black:                           '0x5c5855'
    red:                             '0xdb2d20'
    green:                           '0x01a252'
    yellow:                          '0xfded02'
    blue:                            '0x01a0e4'
    magenta:                         '0xa16a94'
    cyan:                            '0xb5e4f4'
    white:                           '0xf7f7f7'
  indexed_colors:
    - { index:                       16, color: '0xe8bbd0' }
    - { index:                       17, color: '0xcdab53' }
    - { index:                       18, color: '0x3a3432' }
    - { index:                       19, color: '0x4a4543' }
    - { index:                       20, color: '0x807d7c' }
    - { index:                       21, color: '0xd6d5d4' }
  search:
    matches:
     foreground:                     '0xdb2d20'
     background:                     '0xa5a2a2'
    focused_match:
     foreground:                     '0x090300'
     background:                     '0xfded02'
  hints:
    alphabet:                        "jfkdls;ahgurieowpq"
    enabled:
    - regex:                         "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
                                     [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      hyperlinks:                    true
      command:                       open
      post_processing:               true
      mouse:
        enabled:                     true
        mods:                        Command
  footer_bar:
   background:                       '#777777'
   foreground:                       '#000000'

bell:
  animation:                         Linear
  duration:                          10
  color:                             "#000000"

selection:
  semantic_escape_chars:             ",│`|:\"' ()[]{}<>"
  save_to_clipboard:                 true

cursor:
  style:
    shape:                           Block
    blinking:                        Always
  blink_interval:                    550
  blink_timeout:                     5
  vi_mode_style:
    shape:                           Beam
    blinking:                        Always

live_config_reload:                  true

alt_send_esc:                        true

mouse:
  double_click:                      { threshold: 300 }
  triple_click:                      { threshold: 300 }
  hide_when_typing:                  true

key_bindings:
  - { key: A,           mods: Alt,           chars: "\x1ba"                                  }
  - { key: B,           mods: Alt,           chars: "\x1bb"                                  }
  - { key: Back,        chars: "\x7f"                                                        }
  - { key: Back,        mods: Alt,           chars: "\x1b\x7f"                               }
  - { key: Backslash,   mods: Alt,           chars: "\x1b\\"                                 }
  - { key: C,           mods: Alt,           chars: "\x1bc"                                  }
  - { key: C,           mods: Command,       action: Copy                                    }
  - { key: Comma,       mods: Alt,           chars: "\x1b,"                                  }
  - { key: Copy,        action: Copy                                                         }
  - { key: D,           mods: Alt,           chars: "\x1bd"                                  }
  - { key: Delete,      chars: "\x1b[3~"                                                     }
  - { key: Down,        chars: "\x1bOB",     mode: AppCursor                                 }
  - { key: Down,        chars: "\x1b[B",     mode: ~AppCursor                                }
  - { key: Down,        mods: Alt,           chars: "\x1b[1;3B"                              }
  - { key: Down,        mods: Control,       chars: "\x1b[1;5B"                              }
  - { key: Down,        mods: Shift,         chars: "\x1b[1;2B"                              }
  - { key: E,           mods: Alt,           chars: "\x1be"                                  }
  - { key: End,         chars: "\x1bOF",     mode: AppCursor                                 }
  - { key: End,         chars: "\x1b[F",     mode: ~AppCursor                                }
  - { key: Equals,      mods: Command,       action: IncreaseFontSize                        }
  - { key: F,           mods: Alt,           chars: "\x1bf"                                  }
  - { key: F1,          chars: "\x1bOP"                                                      }
  - { key: F1,          mods: Alt,           chars: "\x1b[1;6P"                              }
  - { key: F1,          mods: Command,       chars: "\x1b[1;3P"                              }
  - { key: F1,          mods: Control,       chars: "\x1b[1;5P"                              }
  - { key: F1,          mods: Shift,         chars: "\x1b[1;2P"                              }
  - { key: F10,         chars: "\x1b[21~"                                                    }
  - { key: F10,         mods: Alt,           chars: "\x1b[21;6~"                             }
  - { key: F10,         mods: Command,       chars: "\x1b[21;3~"                             }
  - { key: F10,         mods: Control,       chars: "\x1b[21;5~"                             }
  - { key: F10,         mods: Shift,         chars: "\x1b[21;2~"                             }
  - { key: F11,         chars: "\x1b[23~"                                                    }
  - { key: F11,         mods: Alt,           chars: "\x1b[23;6~"                             }
  - { key: F11,         mods: Command,       chars: "\x1b[23;3~"                             }
  - { key: F11,         mods: Control,       chars: "\x1b[23;5~"                             }
  - { key: F11,         mods: Shift,         chars: "\x1b[23;2~"                             }
  - { key: F12,         chars: "\x1b[24~"                                                    }
  - { key: F12,         mods: Alt,           chars: "\x1b[24;6~"                             }
  - { key: F12,         mods: Command,       chars: "\x1b[24;3~"                             }
  - { key: F12,         mods: Control,       chars: "\x1b[24;5~"                             }
  - { key: F12,         mods: Shift,         chars: "\x1b[24;2~"                             }
  - { key: F2,          chars: "\x1bOQ"                                                      }
  - { key: F2,          mods: Alt,           chars: "\x1b[1;6Q"                              }
  - { key: F2,          mods: Command,       chars: "\x1b[1;3Q"                              }
  - { key: F2,          mods: Control,       chars: "\x1b[1;5Q"                              }
  - { key: F2,          mods: Shift,         chars: "\x1b[1;2Q"                              }
  - { key: F3,          chars: "\x1bOR"                                                      }
  - { key: F3,          mods: Alt,           chars: "\x1b[1;6R"                              }
  - { key: F3,          mods: Command,       chars: "\x1b[1;3R"                              }
  - { key: F3,          mods: Control,       chars: "\x1b[1;5R"                              }
  - { key: F3,          mods: Shift,         chars: "\x1b[1;2R"                              }
  - { key: F4,          chars: "\x1bOS"                                                      }
  - { key: F4,          mods: Alt,           chars: "\x1b[1;6S"                              }
  - { key: F4,          mods: Command,       chars: "\x1b[1;3S"                              }
  - { key: F4,          mods: Control,       chars: "\x1b[1;5S"                              }
  - { key: F4,          mods: Shift,         chars: "\x1b[1;2S"                              }
  - { key: F5,          chars: "\x1b[15~"                                                    }
  - { key: F5,          mods: Alt,           chars: "\x1b[15;6~"                             }
  - { key: F5,          mods: Command,       chars: "\x1b[15;3~"                             }
  - { key: F5,          mods: Control,       chars: "\x1b[15;5~"                             }
  - { key: F5,          mods: Shift,         chars: "\x1b[15;2~"                             }
  - { key: F6,          chars: "\x1b[17~"                                                    }
  - { key: F6,          mods: Alt,           chars: "\x1b[17;6~"                             }
  - { key: F6,          mods: Command,       chars: "\x1b[17;3~"                             }
  - { key: F6,          mods: Control,       chars: "\x1b[17;5~"                             }
  - { key: F6,          mods: Shift,         chars: "\x1b[17;2~"                             }
  - { key: F7,          chars: "\x1b[18~"                                                    }
  - { key: F7,          mods: Alt,           chars: "\x1b[18;6~"                             }
  - { key: F7,          mods: Command,       chars: "\x1b[18;3~"                             }
  - { key: F7,          mods: Control,       chars: "\x1b[18;5~"                             }
  - { key: F7,          mods: Shift,         chars: "\x1b[18;2~"                             }
  - { key: F8,          chars: "\x1b[19~"                                                    }
  - { key: F8,          mods: Alt,           chars: "\x1b[19;6~"                             }
  - { key: F8,          mods: Command,       chars: "\x1b[19;3~"                             }
  - { key: F8,          mods: Control,       chars: "\x1b[19;5~"                             }
  - { key: F8,          mods: Shift,         chars: "\x1b[19;2~"                             }
  - { key: F9,          chars: "\x1b[20~"                                                    }
  - { key: F9,          mods: Alt,           chars: "\x1b[20;6~"                             }
  - { key: F9,          mods: Command,       chars: "\x1b[20;3~"                             }
  - { key: F9,          mods: Control,       chars: "\x1b[20;5~"                             }
  - { key: F9,          mods: Shift,         chars: "\x1b[20;2~"                             }
  - { key: G,           mods: Alt,           chars: "\x1bg"                                  }
  - { key: H,           mods: Alt,           chars: "\x1bh"                                  }
  - { key: H,           mods: Command,       action: Hide                                    }
  - { key: Home,        chars: "\x1bOH",     mode: AppCursor                                 }
  - { key: Home,        chars: "\x1b[H",     mode: ~AppCursor                                }
  - { key: I,           mods: Alt,           chars: "\x1bi"                                  }
  - { key: Insert,      chars: "\x1b[2~"                                                     }
  - { key: J,           mods: Alt,           chars: "\x1bj"                                  }
  - { key: K,           mods: Alt,           chars: "\x1bk"                                  }
  - { key: K,           mods: Command,       action: ClearHistory                            }
  - { key: K,           mods: Command,       chars: "\x0c"                                   }
  - { key: Key0,        mods: Alt,           chars: "\x1b0"                                  }
  - { key: Key0,        mods: Command,       action: ResetFontSize                           }
  - { key: Key1,        mods: Alt,           chars: "\x1b1"                                  }
  - { key: Key2,        mods: Alt,           chars: "\x1b2"                                  }
  - { key: Key3,        mods: Alt,           chars: "\x1b3"                                  }
  - { key: Key4,        mods: Alt,           chars: "\x1b4"                                  }
  - { key: Key5,        mods: Alt,           chars: "\x1b5"                                  }
  - { key: Key6,        mods: Alt,           chars: "\x1b6"                                  }
  - { key: Key7,        mods: Alt,           chars: "\x1b7"                                  }
  - { key: Key8,        mods: Alt,           chars: "\x1b8"                                  }
  - { key: Key9,        mods: Alt,           chars: "\x1b9"                                  }
  - { key: L,           mods: Alt,           chars: "\x1bl"                                  }
  - { key: L,           mods: Control,       action: ClearLogNotice                          }
  - { key: L,           mods: Control,       chars: "\x0c"                                   }
  - { key: LBracket,    mods: Alt,           chars: "\x1b["                                  }
  - { key: LBracket,    mods: Shift|Alt,     chars: "\x1b{"                                  }
  - { key: Left,        chars: "\x1bOD",     mode: AppCursor                                 }
  - { key: Left,        chars: "\x1b[D",     mode: ~AppCursor                                }
  - { key: Left,        mods: Alt,           chars: "\x1b[1;3D"                              }
  - { key: Left,        mods: Control,       chars: "\x1b[1;5D"                              }
  - { key: Left,        mods: Shift,         chars: "\x1b[1;2D"                              }
  - { key: M,           mods: Alt,           chars: "\x1bm"                                  }
  - { key: Minus,       mods: Alt,           chars: "\x1b-"                                  }
  - { key: Minus,       mods: Command,       action: DecreaseFontSize                        }
  - { key: N,           mods: Alt,           chars: "\x1bn"                                  }
  - { key: N,           mods: Control|Shift, action: SpawnNewInstance                        }
  - { key: NumpadEnter, chars: "\n"                                                          }
  - { key: O,           mods: Alt,           chars: "\x1bo"                                  }
  - { key: P,           mods: Alt,           chars: "\x1bp"                                  }
  - { key: PageDown,    chars: "\x1b[6~"                                                     }
  - { key: PageDown,    mods: Control,       chars: "\x1b[6;5~"                              }
  - { key: PageDown,    mods: Shift,         chars: "\x1b[6;2~"                              }
  - { key: PageUp,      chars: "\x1b[5~"                                                     }
  - { key: PageUp,      mods: Control,       chars: "\x1b[5;5~"                              }
  - { key: PageUp,      mods: Shift,         chars: "\x1b[5;2~"                              }
  - { key: Paste,       action: Paste                                                        }
  - { key: Period,      mods: Alt,           chars: "\x1b."                                  }
  - { key: Q,           mods: Alt,           chars: "\x1bq"                                  }
  - { key: Q,           mods: Command,       action: Quit                                    }
  - { key: R,           mods: Alt,           chars: "\x1br"                                  }
  - { key: RBracket,    mods: Alt,           chars: "\x1b]"                                  }
  - { key: RBracket,    mods: Shift|Alt,     chars: "\x1b}"                                  }
  - { key: Return,      mods: Control,       chars: "\x1b[13;5u"                             }
  - { key: Return,      mods: Shift,         chars: "\x1b[13;2u"                             }
  - { key: Right,       chars: "\x1bOC",     mode: AppCursor                                 }
  - { key: Right,       chars: "\x1b[C",     mode: ~AppCursor                                }
  - { key: Right,       mods: Alt,           chars: "\x1b[1;3C"                              }
  - { key: Right,       mods: Control,       chars: "\x1b[1;5C"                              }
  - { key: Right,       mods: Shift,         chars: "\x1b[1;2C"                              }
  - { key: S,           mods: Alt,           chars: "\x1bs"                                  }
  - { key: Semicolon,   mods: Alt,           chars: "\x1b;"                                  }
  - { key: Space,       mods: Shift,         chars: "\x5c\x08 "                              }
  - { key: T,           mods: Alt,           chars: "\x1bt"                                  }
  - { key: Tab,         mods: Shift,         chars: "\x1b[Z"                                 }
  - { key: U,           mods: Alt,           chars: "\x1bu"                                  }
  - { key: Up,          chars: "\x1bOA",     mode: AppCursor                                 }
  - { key: Up,          chars: "\x1b[A",     mode: ~AppCursor                                }
  - { key: Up,          mods: Alt,           chars: "\x1b[1;3A"                              }
  - { key: Up,          mods: Control,       chars: "\x1b[1;5A"                              }
  - { key: Up,          mods: Shift,         chars: "\x1b[1;2A"                              }
  - { key: V,           mods: Alt,           chars: "\x1bv"                                  }
  - { key: V,           mods: Command,       action: Paste                                   }
  - { key: W,           mods: Alt,           chars: "\x1bw"                                  }
  - { key: W,           mods: Command,       action: Quit                                    }
  - { key: X,           mods: Alt,           chars: "\x1bx"                                  }
  - { key: Y,           mods: Alt,           chars: "\x1by"                                  }
  - { key: Z,           mods: Alt,           chars: "\x1bz"                                  }
  - { key: N,           mods: Control,       mode: Search,     action: SearchHistoryNext     }
  - { key: N,           mods: Control|Shift, mode: Search,     action: SearchHistoryPrevious }

