[general]
  import = ["/Users/andrew.snelling/.config/alacritty/base16_default_dark.toml"]

[bell]
  animation = "EaseOutExpo"
  color     = "#000000"
  duration  = 10

[env]
  TERM = "xterm-256color"

[font]
  normal = { family = "Iosevka Nerd Font Propo" }
  size   = 17

[selection]
  save_to_clipboard = true

[window]
  option_as_alt = "Both"

[mouse]
  hide_when_typing = true
