---
bell:
  animation: EaseOutExpo
  color: '#000000'
  duration: 10
cursor:
  blink_interval: 550
  blink_timeout: 0
  style:
    blinking: Always
env:
  TERM: xterm-256color
font:
  bold:
    style: Semibold
  bold_italic:
    style: Semibold Oblique
  draw_bold_text_with_bright_colors: true
  glyph_offset:
    y: 2
  italic:
    style: Light Oblique
  normal:
    family: Iosevka Nerd Font Mono
    style: Light
  offset:
    y: 6
  size: 17
import:
  - ~/.config/alacritty/base16_default_dark.yml
  - ~/.config/alacritty/keybindings.yml
live_config_reload: true
selection:
  save_to_clipboard: true
shell:
  args:
    - --login
    - -c
    - 'tmux attach || tmux'
  program: /usr/local/bin/bash
window:
  decorations: none
  dynamic_padding: true
  option_as_alt: Both
