---
# https://github.com/aarowill/base16-alacritty/blob/master/colors/base16-default-dark.yml
# Base16 Default Dark - alacritty color config
# Chris Kempson (http://chriskempson.com)
colors:
  bright:
    black: '0x585858'
    blue: '0xb8b8b8'
    cyan: '0xa16946'
    green: '0x282828'
    magenta: '0xe8e8e8'
    red: '0xdc9656'
    white: '0xf8f8f8'
    yellow: '0x383838'
  cursor:
    cursor: '0xd8d8d8'
    text: '0x181818'
  normal:
    black: '0x181818'
    blue: '0x7cafc2'
    cyan: '0x86c1b9'
    green: '0xa1b56c'
    magenta: '0xba8baf'
    red: '0xab4642'
    white: '0xd8d8d8'
    yellow: '0xf7ca88'
  primary:
    background: '0x181818'
    foreground: '0xd8d8d8'
