---
# yamllint disable rule:key-ordering
key_bindings:
  - key: A
    mods: Alt
    chars: '\ea'
  - key: A
    mods: Alt|Shift
    chars: '\eA'
  - key: B
    mods: Alt
    chars: '\eb'
  - key: B
    mods: Alt|Shift
    chars: '\eB'
  - key: Backslash
    mods: Alt
    chars: '\e\\'
  - key: Backslash
    mods: Alt|Shift
    chars: '\e|'
  - key: C
    mods: Alt
    chars: '\ec'
  - key: C
    mods: Alt|Shift
    chars: '\eC'
  - key: Comma
    mods: Alt|Shift
    chars: '\e<'
  - key: D
    mods: Alt
    chars: '\ed'
  - key: D
    mods: Alt|Shift
    chars: '\eD'
  - key: E
    mods: Alt
    chars: '\ee'
  - key: E
    mods: Alt|Shift
    chars: '\eE'
  - key: F
    mods: Alt
    chars: '\ef'
  - key: F
    mods: Alt|Shift
    chars: '\eF'
  - key: G
    mods: Alt
    chars: '\eg'
  - key: G
    mods: Alt|Shift
    chars: '\eG'
  - key: Grave
    mods: Alt
    chars: '\e`'
  - key: Grave
    mods: Alt|Shift
    chars: '\e~'
  - key: H
    mods: Alt
    chars: '\eh'
  - key: H
    mods: Alt|Shift
    chars: '\eH'
  - key: I
    mods: Alt
    chars: '\ei'
  - key: I
    mods: Alt|Shift
    chars: '\eI'
  - key: J
    mods: Alt
    chars: '\ej'
  - key: J
    mods: Alt|Shift
    chars: '\eJ'
  - key: K
    mods: Alt
    chars: '\ek'
  - key: K
    mods: Alt|Shift
    chars: '\eK'
  - key: K
    mods: Command
    command:
      program: /usr/local/bin/tmux
      args:
        - send-keys
        - -R
        - C-l
        - ;
        - clear-history
  - key: Key0
    mods: Alt
    chars: '\e0'
  - key: Key1
    mods: Alt
    chars: '\e1'
  - key: Key2
    mods: Alt
    chars: '\e2'
  - key: Key3
    mods: Alt
    chars: '\e3'
  - key: Key3
    mods: Alt|Shift
    chars: '\e#'
  - key: Key4
    mods: Alt
    chars: '\e4'
  - key: Key5
    mods: Alt
    chars: '\e5'
  - key: Key5
    mods: Alt|Shift
    chars: '\e%'
  - key: Key6
    mods: Alt
    chars: '\e6'
  - key: Key6
    mods: Alt|Shift
    chars: '\e^'
  - key: Key7
    mods: Alt
    chars: '\e7'
  - key: Key8
    mods: Alt
    chars: '\e8'
  - key: Key8
    mods: Alt|Shift
    chars: '\e*'
  - key: Key9
    mods: Alt
    chars: '\e9'
  - key: L
    mods: Alt
    chars: '\el'
  - key: L
    mods: Alt|Shift
    chars: '\eL'
  - key: M
    mods: Alt
    chars: '\em'
  - key: M
    mods: Alt|Shift
    chars: '\eM'
  - key: Minus
    mods: Alt|Shift
    chars: '\e_'
  - key: N
    mods: Alt
    chars: '\en'
  - key: N
    mods: Alt|Shift
    chars: '\eN'
  - key: O
    mods: Alt
    chars: '\eo'
  - key: O
    mods: Alt|Shift
    chars: '\eO'
  - key: P
    mods: Alt
    chars: '\ep'
  - key: P
    mods: Alt|Shift
    chars: '\eP'
  - key: Period
    mods: Alt
    chars: '\e.'
  - key: Period
    mods: Alt|Shift
    chars: '\e>'
  - key: Q
    mods: Alt
    chars: '\eq'
  - key: Q
    mods: Alt|Shift
    chars: '\eQ'
  - key: R
    mods: Alt
    chars: '\er'
  - key: R
    mods: Alt|Shift
    chars: '\eR'
  - key: S
    mods: Alt
    chars: '\es'
  - key: S
    mods: Alt|Shift
    chars: '\eS'
  - key: Space
    mods: Control
    chars: '\0'
  - key: T
    mods: Alt
    chars: '\et'
  - key: T
    mods: Alt|Shift
    chars: '\eT'
  - key: U
    mods: Alt
    chars: '\eu'
  - key: U
    mods: Alt|Shift
    chars: '\eU'
  - key: V
    mods: Alt
    chars: '\ev'
  - key: V
    mods: Alt|Shift
    chars: '\eV'
  - key: W
    mods: Alt
    chars: '\ew'
  - key: W
    mods: Alt|Shift
    chars: '\eW'
  - key: X
    mods: Alt
    chars: '\ex'
  - key: X
    mods: Alt|Shift
    chars: '\eX'
  - key: Y
    mods: Alt
    chars: '\ey'
  - key: Y
    mods: Alt|Shift
    chars: '\eY'
  - key: Z
    mods: Alt
    chars: '\ez'
  - key: Z
    mods: Alt|Shift
    chars: '\eZ'
