---
key_bindings:
  - chars: '\ea'
    key: A
    mods: Alt
  - chars: '\eA'
    key: A
    mods: Alt|Shift
  - chars: '\eb'
    key: B
    mods: Alt
  - chars: '\eB'
    key: B
    mods: Alt|Shift
  - chars: '\e\\'
    key: Backslash
    mods: Alt
  - chars: '\e|'
    key: Backslash
    mods: Alt|Shift
  - chars: '\ec'
    key: C
    mods: Alt
  - chars: '\eC'
    key: C
    mods: Alt|Shift
  - chars: '\e<'
    key: Comma
    mods: Alt|Shift
  - chars: '\ed'
    key: D
    mods: Alt
  - chars: '\eD'
    key: D
    mods: Alt|Shift
  - chars: '\ee'
    key: E
    mods: Alt
  - chars: '\eE'
    key: E
    mods: Alt|Shift
  - chars: '\ef'
    key: F
    mods: Alt
  - chars: '\eF'
    key: F
    mods: Alt|Shift
  - chars: '\eg'
    key: G
    mods: Alt
  - chars: '\eG'
    key: G
    mods: Alt|Shift
  - chars: '\e`'
    key: Grave
    mods: Alt
  - chars: '\e~'
    key: Grave
    mods: Alt|Shift
  - chars: '\eh'
    key: H
    mods: Alt
  - chars: '\eH'
    key: H
    mods: Alt|Shift
  - chars: '\ei'
    key: I
    mods: Alt
  - chars: '\eI'
    key: I
    mods: Alt|Shift
  - chars: '\ej'
    key: J
    mods: Alt
  - chars: '\eJ'
    key: J
    mods: Alt|Shift
  - chars: '\ek'
    key: K
    mods: Alt
  - chars: '\eK'
    key: K
    mods: Alt|Shift
  - command:
      args:
        - send-keys
        - -R
        - C-l
        - ;
        - clear-history
      program: /usr/local/bin/tmux
    key: K
    mods: Command
  - chars: '\e0'
    key: Key0
    mods: Alt
  - chars: '\e1'
    key: Key1
    mods: Alt
  - chars: '\e2'
    key: Key2
    mods: Alt
  - chars: '\e3'
    key: Key3
    mods: Alt
  - chars: '\e#'
    key: Key3
    mods: Alt|Shift
  - chars: '\e4'
    key: Key4
    mods: Alt
  - chars: '\e5'
    key: Key5
    mods: Alt
  - chars: '\e%'
    key: Key5
    mods: Alt|Shift
  - chars: '\e6'
    key: Key6
    mods: Alt
  - chars: '\e^'
    key: Key6
    mods: Alt|Shift
  - chars: '\e7'
    key: Key7
    mods: Alt
  - chars: '\e8'
    key: Key8
    mods: Alt
  - chars: '\e*'
    key: Key8
    mods: Alt|Shift
  - chars: '\e9'
    key: Key9
    mods: Alt
  - chars: '\el'
    key: L
    mods: Alt
  - chars: '\eL'
    key: L
    mods: Alt|Shift
  - chars: '\em'
    key: M
    mods: Alt
  - chars: '\eM'
    key: M
    mods: Alt|Shift
  - chars: '\e_'
    key: Minus
    mods: Alt|Shift
  - chars: '\en'
    key: N
    mods: Alt
  - chars: '\eN'
    key: N
    mods: Alt|Shift
  - chars: '\eo'
    key: O
    mods: Alt
  - chars: '\eO'
    key: O
    mods: Alt|Shift
  - chars: '\ep'
    key: P
    mods: Alt
  - chars: '\eP'
    key: P
    mods: Alt|Shift
  - chars: '\e.'
    key: Period
    mods: Alt
  - chars: '\e>'
    key: Period
    mods: Alt|Shift
  - chars: '\eq'
    key: Q
    mods: Alt
  - chars: '\eQ'
    key: Q
    mods: Alt|Shift
  - chars: '\er'
    key: R
    mods: Alt
  - chars: '\eR'
    key: R
    mods: Alt|Shift
  - chars: '\es'
    key: S
    mods: Alt
  - chars: '\eS'
    key: S
    mods: Alt|Shift
  - chars: '\0'
    key: Space
    mods: Control
  - chars: '\et'
    key: T
    mods: Alt
  - chars: '\eT'
    key: T
    mods: Alt|Shift
  - chars: '\eu'
    key: U
    mods: Alt
  - chars: '\eU'
    key: U
    mods: Alt|Shift
  - chars: '\ev'
    key: V
    mods: Alt
  - chars: '\eV'
    key: V
    mods: Alt|Shift
  - chars: '\ew'
    key: W
    mods: Alt
  - chars: '\eW'
    key: W
    mods: Alt|Shift
  - chars: '\ex'
    key: X
    mods: Alt
  - chars: '\eX'
    key: X
    mods: Alt|Shift
  - chars: '\ey'
    key: Y
    mods: Alt
  - chars: '\eY'
    key: Y
    mods: Alt|Shift
  - chars: '\ez'
    key: Z
    mods: Alt
  - chars: '\eZ'
    key: Z
    mods: Alt|Shift
