---
blocks:
  - permission
  - user
  - group
  - size
  - date
  - name
classic: false
color:
  theme: default
  when: auto
date: date
dereference: false
header: false
hyperlink: never
icons:
  separator: ' '
  theme: fancy
  when: auto
ignore-globs:
  - .git
  - node_modules
indicators: true
layout: oneline
no-symlink: false
permission: rwx
recursion:
  depth: 2
  enabled: false
size: default
sorting:
  column: name
  dir-grouping: first
  reverse: false
symlink-arrow: ⇒
total-size: false
