style: auto # style name or JSON path (default "auto")
local: false # show local files only; no network (TUI-mode only)
mouse: false # mouse support (TUI-mode only)
pager: true # use pager to display markdown
width: 80 # word-wrap at width
