[flags]
 battery           = true
 enable_gpu_memory = true
 rate              = 500
 tree              = true

[colors]
 arc_color     = "#7cafc2"
 avg_cpu_color = "#e8e8e8"
 border_color  = "#d8d8d8"

 cpu_core_colors = [
  "#ab4642",
  "#dc9656",
  "#f7ca88",
  "#a1b56c",
  "#86c1b9",
  "#7cafc2",
  "#ba8baf",
  "#a16946",
  "#ab4642",
  "#dc9656",
  "#f7ca88",
  "#a1b56c",
  "#86c1b9",
  "#7cafc2",
  "#ba8baf",
  "#a16946",
 ]
 gpu_core_colors = [
  "#dc9656",
  "#f7ca88",
  "#a1b56c",
  "#86c1b9",
  "#7cafc2",
  "#ba8baf",
  "#a16946",
 ]

 graph_color              = "#d8d8d8"
 high_battery_color       = "#a1b56c"
 highlighted_border_color = "#f7ca88"
 low_battery_color        = "#ab4642"
 ram_color                = "#ba8baf"
 rx_color                 = "#7cafc2"
 selected_bg_color        = "#86c1b9"
 selected_text_color      = "#181819"
 swap_color               = "#f7ca88"
 table_header_color       = "#86c1b9"
 text_color               = "#d8d8d8"
 tx_color                 = "#a1b56c"
 widget_title_color       = "#d8d8d8"

[[row]]
 [[row.child]]
  type = "cpu"
[[row]]
 [[row.child]]
  ratio = 4
  type  = "memory"
 [[row.child]]
  ratio = 3
  [[row.child.child]]
   type = "temperature"
  [[row.child.child]]
   type = "disk"
  [[row.child.child]]
   type = "battery"
[[row]]
 [[row.child]]
  type = "network"
 [[row.child]]
  default = true
  type    = "processes"
