"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
  prepend_keymap = [
    { desc = "Maximize or restore the preview pane", on = "T", run = "plugin toggle-pane max-preview" },
    { desc = "Open the file under the cursor", on = "<Enter>", run = "plugin smart-enter" },
  ]
