"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
  prepend_keymap = [
    { desc = "Chmod on selected files", on = [
      "c",
      "m",
    ], run = "plugin chmod" },
    { desc = "Maximize or restore the preview pane", on = "T", run = "plugin toggle-pane max-preview" },
    { desc = "Move down, with wrap", on = "j", run = "plugin arrow 1" },
    { desc = "Move up, with wrap", on = "k", run = "plugin arrow -1" },
    { desc = "Run lazygit", on = [
      "g",
      "i",
    ], run = "plugin lazygit" },
    { desc = "cd back to the root of the current Git repository ", on = [
      "g",
      "r",
    ], run = ''' shell 'ya emit cd "$(git rev-parse --show-toplevel)"' ''' },
  ]
