#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
  linemode    = "mtime"
  ratio       = [1, 3, 4]
  show_hidden = true
  sort_by     = "natural"

[plugin]
  prepend_fetchers = [
    { url = "*", run = "git", group = "git" },
    { url = "*/", run = "git", group = "git" },
  ]
