on:
  push:
    branches:
      - main
  pull_request:
jobs:
  TOMBI:
    name: Tombi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: tombi-toml/setup-tombi@v1.1.5
      - run: tombi lint
