---
on: [push]
jobs:
  YAMLLINT:
    name: YAML
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/setup-python@v2'
        with:
          python-version: '3.8'
      - name: yamllint
        run: |
          echo "Installing yamllint..."
          pip install yamllint==1.27.1 --use-pep517
      - name: Run yamllint
        run: |
          echo "Linting with yamllint"
          yamllint . --format github
