---
on: [push]
jobs:
  YAMLFMT:
    name: YAML Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install yamlfmt
        run: |
          echo "Installing yamlfmt..."
          go install github.com/google/yamlfmt/cmd/yamlfmt@latest
      - name: Run yamlfmt
        run: |
          echo "Formatting with yamlfmt"
          yamlfmt -lint
  YAMLLINT:
    name: YAML Lint
    needs: [YAMLFMT]
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/setup-python@v2'
        with:
          python-version: '3.8'
      - name: yamllint
        run: |
          echo "Installing yamllint..."
          pip install yamllint==1.27.1 --use-pep517
      - name: Run yamllint
        run: |
          echo "Linting with yamllint"
          yamllint . --format github
